my_project:
  outputs:
    dev:
      dbname: db
      host: db
      pass: "{{ env_var('POSTGRES_ROOT_PASSWORD') }}"
      port: 5432
      schema: dev
      threads: 1
      type: postgres
      user: db_user
  target: dev
